version: "3"

# builds two containers of the vulnerable webserver
services:
  ubuntu-01:
    user: apache
    container_name: ubuntu-01
    image: apache-2.4.49-vul-demo:latest
    build: .
    ports:
      - 8081:8080
      - 5901:5901
    environment:
      - vncpassword=apache
    volumes:
      - type: bind
        source: ./ssh/ubuntu-01/ubuntu-01
        target: /home/apache/.ssh/ubuntu-01
      - type: bind
        source: ./ssh/ubuntu-01/ubuntu-01.pub
        target: /home/apache/.ssh/ubuntu-01.pub
      - type: bind
        source: ./ssh/ubuntu-01/known_hosts
        target: /home/apache/.ssh/known_hosts
      - type: bind
        source: ./.bash_history
        target: /home/apache/.bash_history

  ubuntu-02:
    user: apache
    container_name: ubuntu-02
    image: apache-2.4.49-vul-demo:latest
    build: .
    ports:
      - 8082:8080
      - 5902:5901
      - 2022:22
    environment:
      - vncpassword=apache
    volumes:
      - type: bind
        source: ./ssh/ubuntu-02/ubuntu-02
        target: /home/apache/.ssh/ubuntu-02
      - type: bind
        source: ./ssh/ubuntu-02/ubuntu-02.pub
        target: /home/apache/.ssh/ubuntu-02.pub
      - type: bind
        source: ./ssh/ubuntu-02/authorized_keys
        target: /home/apache/.ssh/authorized_keys
