version: "3"

# builds two containers of the vulnerable webserver
services:
  ubuntu-01:
    container_name: ubuntu-01
    image: apache-2.4.49-vul-demo:latest
    build: .
    ports:
      - 8081:8080
      - 5901:5901
    environment:
      - vncpassword=apache
  ubuntu-02:
    container_name: ubuntu-02
    image: apache-2.4.49-vul-demo:latest
    build: .
    ports:
      - 8082:8080
      - 5902:5901
      - 2022:22
    environment:
      - vncpassword=apache
